<section class="col-sm-6 col-md-4 col-sm-offset-3 col-md-offset-4">
    <div class="login-box ">
        <div class="col-sm-8 col-sm-offset-2">
            <a class="" href="/"><img class="img" class="img-responsive" src="<?php echo $this->baseUrl('images/logo.jpg'); ?>" alt="NATAU - Namibia Logo" width="180px" height="150px" /></a>
        </div>
        
        <div class="col-sm-12">
            <hr/>
        </div>
        <section>
             <?php  echo $this->form; ?>
        </section>                 
    </div>
    
</section>