<section class="">
    <p>
        <?php echo $this->partial('/partials/_notices.phtml',array('flashMessages'=>$this->flashMessages())) ?>                        
    </p>
    		<section>
                    <p>
                        Please Provide your details bellow
                    </p>
                    <div>
                        <?php //echo $this->form; ?>

                        
    		<section>
                    <div>
                        <?php //echo $this->form; ?>
                        <form method="post" action="/transmissionlicense/sectionb/" enctype="multipart/form-data" name="frmECB">
                                        <fieldset>
                                            <legend>Member Application Details</legend>
                                             <table>
                                                 <thead>
                                                 </thead>
                                                 <tbody>
                                                     <tr>
                                                         <td><label class="col" for="company_name">Company Name</label></td>
                                                         <td><input type="text" class="col_12" name="company_name" /></td>
                                                     <td></td>
                                                     </tr>
                                                     <tr>
                                                         <td><label class="col" for="telephone_number">Telephone No:</label></td>
                                                         <td><input type="text" class="col_12" name="telephone_number" /></td>
                                                     <td></td>
                                                     </tr>
                                                     <tr>
                                                         <td><label class="col" for="fax_number">Fax No:</label></td>
                                                         <td><input type="text" class="col_12" id="fax_number" name="fax_number" /></td>
                                                     <td></td>
                                                     </tr> 
                                                     <tr>
                                                         <td><label class="col" for="contact_person">Contact Person:</label></td>
                                                         <td><input type="text" class="col_12  " value="" id="contact_person" name="contact_person"/></td>
                                                     <td></td>
                                                     </tr>                                                      
                                                     
                                                     <tr>
                                                     </tr>
                                                     <tr>
                                                         <td><label class="col" for="email_address">E-mail Address:</label></td>
                                                         <td><input type="text" class="col_12  " value="" id="email_address" name="email_address"/></td>
                                                         <td></td>
                                                     </tr>
                                                     <tr>
                                                         <td><label class="col" for="postal_address">Postal Address</label></td>
                                                         <td><input type="text" class="col_12" id="postal_address" name="postal_address" /></td>
                                                         <td></td>
                                                     </tr>                                                     
                                                 </tbody>
                                                 <tfoot>

                                                 </tfoot>
                                             </table>                                                     
                                        </fieldset>
                            <hgroup>
                                <button name="cmd_save" id="cmd_save" class="col_3 frm-btn green column" type="submit"><i class="icon-save"></i> Save C Data</button>
                            </hgroup>                            
                                     </form>

                                 </div>
                                 <?php ?>
                             </section>                       

                        <section>
                        </section>
                  

                        
                    </div>
                    <?php ?>
		</section>
</section>