<?php echo $this->partial('/partials/_title.phtml',array('title'=>$this->title)) ?>  		
<section class="">
    <p>
        <?php echo $this->partial('/partials/_notices.phtml',array('flashMessages'=>$this->flashMessages(),
                                                                   'errors'=>$this->errors,)) ?>                        
    </p>
    		<section>

                    <div> 
                        <table width="35%" align="center" style="border:10px solid #00ccff; padding:40px;">
                            <tbody>
                                <tr style="background: none;">
                                    <td align="center" style="font-family:Arial, Helvetica, sans-serif; color:#666666;text-align: center; font-size:20px;font-weight:bold;">
                                    Thank You!
                                    </td>
                                </tr>
                                <tr style="background: none;">
                                    <td height="7"></td>
                                </tr>
                                <tr style="background: none;">
                                    <td align="center" style="font-family:Arial, Helvetica, sans-serif;text-align: left; color:#666666; font-size:14px;">                                   
                                        <p>Thank you very much for opening a new ECB-CLEMS account.</p>
                                        <p>&nbsp;</p>
                                        <p>A confirmation message with your new account data and further information has been sent to your email address: innocent.blacius@live.com.</p>
                                        <p>&nbsp;</p> 
                                        <p><strong>Thank you for your interest in ECB and its Services!</strong></p>
                                        <p>&nbsp;</p>                                    
                                    </td>

                                </tr>
                                <tr style="background: none;">
                                    <td align="center" style="font-family:Arial, Helvetica, sans-serif;text-align: left; color:#666666; font-size:14px;">

                                        <p>The ECB-CLEMS team</p>
                                        <p>&nbsp;</p>                                    
                                    </td>

                                </tr>                                
                            </tbody>
                        </table>
                        
                    </div>
                    <?php ?>
		</section>
</section>