<!-- ===================================== START FOOTER ===================================== -->

    <article>
        <section class="col-md-4">
            <h5>Contact</h5>
        </section>
        <section class="col-md-4">
            <p>P.O. Box 7516</p>
            <p>Windhoek, Namibia</p>
            <p>P.O. Box 7516</p>
            <p>P.O. Box 7516</p>
            <p>P.O. Box 7516</p>
            
        </section>
        <section class="col-md-4">
            
        </section>
    </article>
<!-- ===================================== END FOOTER ===================================== -->