<!-- ===================================== END HEADER ===================================== -->
<div class="container callout">
    <div class="grid" id="app-header">
        <div class="col_12 app-header">
            <header>
                <div class="col_2 logowrap">
                    <img src="<?php echo $this->baseUrl('images/logo.jpg'); ?>" alt="NATAU - Namibia Logo" width="180px" height="150px" />
                </div>
                <div class="col_3">
                    <h5>NATAU MIS</h5>
                </div>
                <div class="col_3">

                </div>
                <div class="col_4 float-right" id="metaData">
                    <em class="right"><?php echo $this->loggedIn(); ?></em> 
                </div>                
            </header>	
        </div>
    </div>
</div>
<div class="container callout">
    <div class="grid" id="app-menu-wrapper">
        <div class="col_12 app-menu -top-margin">
            <!--<nav>
                    <ul class="menu">
                    <li class="current"><a href=# title="System Settings"><i class="icon-cogs"></i>System Setting</a></li>
                    <li><a href=# title="Account Settings">Account Setting</a></li>
                    <li><a href=# title="Users">Users</a></li>
                    <li><a href=# title="System Settings">Dashboards</a></li>
                    <li><a href=# title="System Settings">Applications</a></li>
                    </ul>
            </nav>	-->
        </div>
        <header class="col_12 -top-margin" id="title-calout">
            <div class="col_6 title-text inner"><h5>NATAU MIS : Admin Section</h5></div>
            <div class="col_6"></div>
        </header>
    </div><!-- END GRID-->
</div>
<!-- ===================================== END HEADER ===================================== -->