<?php echo $this->doctype(); ?>

<html lang="en" dir="ltr">
<head>
<?php echo $this->headTitle(); ?>
<?php echo $this->headMeta(); ///exit('default layout');?>
    
<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/bootstrap.min.css') ?>" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/bootstrap-datepicker.css') ?>" type="text/css" media="all">

<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/font-awesome.min.css') ?>" type="text/css" media="all">

<link rel="stylesheet" href="<?php echo  $this->baseUrl('libs/jquery/ui/themes/base/minified/jquery-ui.min.css') ?>" type="text/css" media="all">

<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/style.css') ?>" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/natau.css') ?>" type="text/css" media="all">

<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/www.css') ?>" type="text/css" media="all">


<script src="<?php echo  $this->baseUrl('libs/jquery/1.10.2/jquery.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/ui/1.10.3/minified/jquery.ui.core.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/ui/1.10.3/minified/jquery.ui.widget.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('js/bootstrap-datepicker.js'); ?>"></script>

<script src="<?php echo  $this->baseUrl('libs/jquery/ui/1.10.3/minified/jquery.ui.datepicker.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/tools/validate.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/calculation/jquery.calculation.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/tiny-mce/jquery.tinymce.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/ckeditor/ckeditor.js'); ?>"></script>
<!-- <script src="<?php echo  $this->baseUrl('libs/jquery/ddaccordion/ddaccordion.js'); ?>"></script> -->
<script src="<?php echo  $this->baseUrl('scripts/kickstart.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/moam/moam.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('js/setup.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('js/natau.js'); ?>"></script>
<!--  Style -->

<!-- .......... -->
<!--[if lt IE 9]>
<link rel="stylesheet" href="styles/ie.css" type="text/css" media="all">
<script src="scripts/ie/css3-mediaqueries.min.js"></script>
<script src="scripts/ie/ie9.js"></script>
<script src="scripts/ie/html5shiv.min.js"></script>
<![endif]-->
    <script type="text/javascript" src="<?php echo  $this->baseUrl('js/setup.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo  $this->baseUrl('js/natau.js'); ?>"></script>
   <?php $this->headLink()
                          ->appendStylesheet($this->baseUrl('/css/natau.css'));?>
    <?php echo $this->navigation()->links(); ?>
   <?php echo $this->headLink(); ?>
   <?php echo $this->headScript(); ?>
</head>
<body class="natau login" onload="">
<div id="page">
<?php // echo $this->render('www-header.phtml'); ?>
<div id="body" class="container">
    <section class="row">
        <section class="col-md-12">
                               <!-- Content -->
                        <?php echo $this->layout()->content; ?>
        </section>       
    </section>
</div>
</div>
</body>
</html>