<!-- ===================================== START FOOTER ===================================== -->
<article class="row">
        <section class="col-md-6 has-underline">
            <h5>Our Contact Details</h5>            
        </section>
        <section class="col-md-6"></section>
    </article>
<article class="row">
        <section class="col-md-4">
            <p>Tel : +264 61 217244</p>
            <p>Fax : +264-61-263767</p>
            <p>E-mail : natau@mweb.com.na</p>
            <p>Website : www.natau.org</p> 
        </section>    
        <section class="col-md-4">
            <p>P.O. Box 7516</p>
            <p>Windhoek, Namibia</p>
            <p>Erf No: 8506, Mungunda Street, Katutura</p>             
        </section>
        <section class="col-md-4">
            
        </section>
    </article>
<!-- ===================================== END FOOTER ===================================== -->