<?php echo $this->doctype(); ?>

<html lang="en" dir="ltr">
<head>
<?php echo $this->headTitle(); ?>
<?php echo $this->headMeta(); ///exit('default layout');?>
    
<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/bootstrap.min.css') ?>" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/bootstrap-datepicker.css') ?>" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/bootstrap-dialog.css') ?>" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo  $this->baseUrl('libs/jquery/zebra/dialog/css/flat/zebra_dialog.css') ?>" type="text/css" media="all">

<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/font-awesome.min.css') ?>" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/ionicons-1.5.2/css/ionicons.min.css') ?>" type="text/css" media="all">
<link rel="stylesheet" href="<?php echo  $this->baseUrl('libs/jquery/ui/themes/base/minified/jquery-ui.min.css') ?>" type="text/css" media="all">

<link rel="stylesheet" href="<?php echo  $this->baseUrl('css/style.css') ?>" type="text/css" media="all">

<script src="<?php echo  $this->baseUrl('libs/jquery/1.10.2/jquery.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/ui/1.10.3/minified/jquery.ui.core.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/ui/1.10.3/minified/jquery.ui.widget.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('js/bootstrap-datepicker.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('js/bootstrap-dialog.js'); ?>"></script>


<script src="<?php echo  $this->baseUrl('libs/jquery/tools/validate.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/calculation/jquery.calculation.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/tiny-mce/jquery.tinymce.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/ckeditor/ckeditor.js'); ?>"></script>
<!-- <script src="<?php echo  $this->baseUrl('libs/jquery/ddaccordion/ddaccordion.js'); ?>"></script> -->
<script src="<?php echo  $this->baseUrl('scripts/kickstart.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/moam/moam.min.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/zebra/dialog/zebra_dialog.js'); ?>"></script>
<script src="<?php echo  $this->baseUrl('libs/jquery/calx/jquery-calx-1.1.9.min.js'); ?>"></script>
<!--  Style -->

<!-- .......... -->
<!--[if lt IE 9]>
<link rel="stylesheet" href="styles/ie.css" type="text/css" media="all">
<script src="scripts/ie/css3-mediaqueries.min.js"></script>
<script src="scripts/ie/ie9.js"></script>
<script src="scripts/ie/html5shiv.min.js"></script>
<![endif]-->

   <?php $this->headLink()
                          ->appendStylesheet($this->baseUrl('/css/natau.css'));?>
    <?php echo $this->navigation()->links(); ?>
   <?php echo $this->headLink(); ?>
   <?php echo $this->headScript(); ?>
</head>
<body class="natau" onload="">
<div id="page">
<?php // echo $this->render('www-header.phtml'); ?>
<div id="menu" class="navbar navbar-default" role="navigation">    
    <header id="has-metadata" class="container">
        <section class="text-right">
			<ul class="meta-data">
                               <li><?php echo $this->loggedInUser();  ?></li>
			</ul>             
        </section>
            <div class="navbar-header">
                <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
                <div id="logo">
                    <a class="navbar-brand" href="/"><img class="img" src="<?php echo $this->baseUrl('images/logo.jpg'); ?>" alt="NATAU - Namibia Logo" width="180px" height="150px" />NATAU NAMIBIA</a>
                </div>
            </div>
            <div class="navbar-collapse collapse">
                <?php $mainnav = $this->navigation()->findOneByLabel('Home');
                echo $this->navigation()->menu()->setMaxDepth(0)->renderMenu($mainnav , array(
                    'ulClass'=>'nav navbar-nav',
                    'liClass'=>'nav'
                ));            
                ?>            
            </div>
    </header>   
</div>

<div id="body" class="container">
<nav class="">
    <div class="breadcrumb">
                        <?php
                        echo $this->navigation()
                                   ->breadcrumbs()
                                   ->setLinkLast(true)
                                   ->setSeparator(' / ');
                ?> 
    </div>
    <div class="page-header">
        <?php echo $this->partial('/partials/_title.phtml',array('title'=>$this->title)) ?> 
    </div>               
</nav>

        <section class="col-md-12">
                               <!-- Content -->
                        <?php echo $this->layout()->content; ?>
        </section>
</div>
    <div id="footer">
    <footer id="" class="container">
        <?php echo $this->render('www-footer.phtml'); ?>
    </footer>        
    </div>
</div>
    <script type="text/javascript" src="<?php echo  $this->baseUrl('js/setup.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo  $this->baseUrl('js/natau.js'); ?>"></script>
</body>
</html>