<header class="app-meta">
    <ul>
        <li>
            <h6>
                Application Type : <span><?php echo $this->escape($this->application_type) ;?></span>
            </h6>
        </li>
        <li>
            <h6>
                Application Number : <span><?php echo $this->escape($this->application_number) ;?></span>
            </h6>
        </li>
        <li>
            <h6>
                Applicant Name :<span> <?php echo $this->escape($this->applicant_name) ;?></span>
            </h6>
        </li>        
    </ul>  
</header>