<?php if ( 0 < count($this->contribution)): ?>
<tr id="row_1">
    <td class="year"><?php echo $this->formSelect('year[]' , null ,['class'=>'form-control' , 'multiple' => FALSE , 'id' => 'A1'] , $this->years); ?></td>
    <td><input type="text" value="" id="B1" name="january[]" class="form-control"></td>
    <td><input type="text" value="" id="C1" name="february[]" class="form-control"></td>
    <td><input type="text" value="" id="D1" name="march[]" class="form-control"></td>
    <td><input type="text" value="" id="E1" name="april[]" class="form-control"></td>
    <td><input type="text" value="" id="F1" name="may[]" class="form-control"></td>
    <td><input type="text" value="" id="G1" name="june[]" class="form-control"></td>
    <td><input type="text" value="" id="H1" name="july[]" class="form-control"></td>
    <td><input type="text" value="" id="I1" name="august[]" class="form-control"></td>
    <td><input type="text" value="" id="J1" name="september[]" class="form-control"></td>
    <td><input type="text" value="" id="K1" name="october[]" class="form-control"></td>
    <td><input type="text" value="" id="L1" name="november[]" class="form-control"></td>
    <td><input type="text" value="" id="M1" name="december[]" class="form-control"></td>
    <td><input type="text" readonly="readonly" value="" id="N1" name="total[]" class="form-control total"></td>
    <td><button onclick="javascript:void(0)" type="button" title="" data-toggle="tooltip" data-widget="remove" class="btn btn-default btn-sm" data-original-title="Remove"><i class="fa fa-times"></i></button></td>
</tr>
<?php else:?>

<?php endif; ?>