<?php if ($this->pageCount > 1): ?>
<section class="row">
    <div class="col-lg-10">
        <div class="paginationControl pagination">
                <!-- Previous page link -->
                                <?php if (isset($this->previous)): ?>
                                        <a class="previous" href="<?php echo $this->url(array('page' => $this->previous)); ?>">Previous</a>
                                <?php else: ?>
                                        <span class="disabled previous">Previous</span>
                                <?php endif; ?>
                <!-- Numbered page links -->
                        <?php foreach ($this->pagesInRange as $page): ?>
                                <?php if ($page != $this->current): ?>
                                        <a  class="current" href="<?php echo $this->url(array('page' => $page)); ?>">
                                        <?php echo $page; ?>
                                        </a>
                                <?php else: ?>
                                        <span class="page">
                                        <?php echo $page; ?> 
                                        </span>
                                <?php endif; ?>
                        <?php endforeach; ?>
                <!-- Next page link -->
                                <?php if (isset($this->next)): ?>
                                        <a class="next" href="<?php echo $this->url(array('page' => $this->next)); ?>">
                                        Next
                                        </a>
                                <?php else: ?>
                                        <span class="disabled next">Next</span>
                                <?php endif; ?>
        </div>
         &verbar; Showing   <?php echo $this->current; ?> out of <?php echo $this->pageCount; ?> pages
    </div>
    <div class="col-lg-2 pagination">
           
    </div>    
</section>
<?php endif; ?>