<?php echo $this->partial('/partials/_title.phtml',array('title'=>$this->title)) ?>  		
<section class="">
    <p>
        <?php echo $this->partial('/partials/_notices.phtml',array('flashMessages'=>$this->flashMessages())) ?>                        
    </p>
    </section>
    		<section>
                    <p>
                        Please Choose the Nature and Type of License you wish to apply for bellow
                    </p>
                    <div>
                        <?php echo $this->form; ?>
                    </div>
                  <!--  <ul class="icons">
                        <li><a href="<?php echo $this->escape($this->url(array('controller'=>'references','action'=>'codes','module'=>'') , null , true)) ?>">Manage Reference Codes</a></li>
                        <li><a href="<?php echo $this->escape($this->url(array('controller'=>'references','action'=>'types','module'=>'') , null , true)) ?>">Manage Reference Types</a></li>
                        
                    </ul> -->
                    <?php ?>
		</section>
   <section class="col_12">
    <div class="col_6 column">
        <h5><i class="icon-tasks"></i> New Applications</h5>
	<table cellspacing="0" cellpadding="0" class="sortable list">
	<thead><tr class="alt first last">
		<th rel="0" value="Name">Application No</th>
		<th rel="1" value="Number">Applicant Name</th>
		<th rel="2" value="Color">Status</th>
		<th rel="3" value="Actions">Actions</th>
	</tr></thead>
	<tbody><tr class="first">
		<td value="Joshua">G-122013</td>
		<td value="555-4325">Innocent Energy</td>
		<td value="Blue">Submitted</td>
		<td value=" 
		"><a href="/applicationreview/transmission/"><i class="icon-pencil"></i></a> 
		<a href=""><i class="icon-minus-sign"></i></a></td>
	</tr>
	<tbody><tr class="first">
		<td value="Joshua">G-122013</td>
		<td value="555-4325">Innocent Energy</td>
		<td value="Blue">Submitted</td>
		<td value=" 
		"><a href=""><i class="icon-pencil"></i></a> 
		<a href=""><i class="icon-minus-sign"></i></a></td>
	</tr>
    	<tbody><tr class="first">
		<td value="Joshua">G-122013</td>
		<td value="555-4325">Innocent Energy</td>
		<td value="Blue">Submitted</td>
		<td value=" 
		"><a href=""><i class="icon-pencil"></i></a> 
		<a href=""><i class="icon-minus-sign"></i></a></td>
	</tr>
    	<tbody><tr class="first">
		<td value="Joshua">G-122013</td>
		<td value="555-4325">Innocent Energy</td>
		<td value="Blue">Submitted</td>
		<td value=" 
		"><a href=""><i class="icon-pencil"></i></a> 
		<a href=""><i class="icon-minus-sign"></i></a></td>
	</tr>
    	<tbody><tr class="first">
		<td value="Joshua">G-122013</td>
		<td value="555-4325">Innocent Energy</td>
		<td value="Blue">Submitted</td>
		<td value=" 
		"><a href=""><i class="icon-pencil"></i></a> 
		<a href=""><i class="icon-minus-sign"></i></a></td>
	</tr>
    	<tbody><tr class="first">
		<td value="Joshua">G-122013</td>
		<td value="555-4325">Innocent Energy</td>
		<td value="Blue">Submitted</td>
		<td value=" 
		"><a href=""><i class="icon-pencil"></i></a> 
		<a href=""><i class="icon-minus-sign"></i></a></td>
	</tr>    
</tbody>
	</table>
	</div>
     <div class="col_6 column">
	<h5>Reviewed Applications</h5>
	<table cellspacing="0" cellpadding="0" class="sortable list">
	<thead><tr class="alt first last">
		<th rel="0" value="Name">Application No</th>
		<th rel="1" value="Number">Applicant Name</th>
		<th rel="2" value="Color">Reviewed</th>
		<th rel="3" value="Actions">Actions</th>
	</tr></thead>
	<tbody><tr class="first">
		<td value="Joshua">G-122013</td>
		<td value="555-4325">Innocent Energy</td>
		<td value="Blue">Pending</td>
		<td value=" 
		"><a href=""><i class="icon-pencil"></i></a> 
		<a href=""><i class="icon-minus-sign"></i></a></td>
	</tr>
	<tbody><tr class="first">
		<td value="Joshua">G-122013</td>
		<td value="555-4325">Innocent Energy</td>
		<td value="Blue">Reviewed</td>
		<td value=" 
		"><a href=""><i class="icon-pencil"></i></a> 
		<a href=""><i class="icon-minus-sign"></i></a></td>
	</tr>
    	<tbody><tr class="first">
		<td value="Joshua">G-122013</td>
		<td value="555-4325">Innocent Energy</td>
		<td value="Blue">Reviewed</td>
		<td value=" 
		"><a href=""><i class="icon-pencil"></i></a> 
		<a href=""><i class="icon-minus-sign"></i></a></td>
	</tr>
    	<tbody><tr class="first">
		<td value="Joshua">G-122013</td>
		<td value="555-4325">Innocent Energy</td>
		<td value="Blue">Submitted</td>
		<td value=" 
		"><a href=""><i class="icon-pencil"></i></a> 
		<a href=""><i class="icon-minus-sign"></i></a></td>
	</tr>
    	<tbody><tr class="first">
		<td value="Joshua">G-122013</td>
		<td value="555-4325">Innocent Energy</td>
		<td value="Blue">Submitted</td>
		<td value=" 
		"><a href=""><i class="icon-pencil"></i></a> 
		<a href=""><i class="icon-minus-sign"></i></a></td>
	</tr>
    	<tbody><tr class="first">
		<td value="Joshua">G-122013</td>
		<td value="555-4325">Innocent Energy</td>
		<td value="Blue">Submitted</td>
		<td value=" 
		"><a href=""><i class="icon-pencil"></i></a> 
		<a href=""><i class="icon-minus-sign"></i></a></td>
	</tr>    
</tbody>
	</table>
	</div>
</section>

<section class="col_12">
    <div class="col_6">

            <h5><i class="icon-envelope-alt"></i> Messages</h5>

        <div class="message-container">
            <div class="messages-list">
            <article class="message">
                <p>
                    wwwwwwwwwwwww wwwwwwwwwww wwwwwwww wwwwwwwwwww wwwwww wwwwwwwwww
                    wwwwwwwwwwwww wwwwwww
                </p>
                <footer>
                    <em class="sender">Innocent J</em>
                </footer>                
            </article>
            <hr/>            
            <article class="message">
                <p>
                    wwwwwwwwwwwww wwwwwwwwwwww wwwwwwwwwwwwwww wwwwwwwwwwww wwwwwww
                   
                </p>
                <footer>
                    <em class="sender">Innocent J</em>
                </footer>                
            </article>
            <hr/>            
            <article class="message">
                <p>
                    wwwwww wwwwwwwwwwwwwww wwwwwwwwwwwwww wwwwwwwwww wwwwwwwwwwwwww
                   
                </p>
                <footer>
                    <em class="sender">Innocent J</em>
                </footer>                
            </article>
            <hr/>            
            <article class="message">
                <p>
                    wwwwwwww wwwwwwwwwww wwwwwwwwwwwww wwwwwwwwwwwwww wwwwww wwwwwww
                   
                </p>
                <footer>
                    <em class="sender">Innocent J</em>
                </footer>                
            </article>
            <hr/>
            <article class="message">
                <p>
                    wwwwwwwwwwwww wwwwwwwwwww wwwwwwwwwww wwwwwwwwwwwwww wwwwwwwwww
                 
                </p>
                <footer>
                    <em class="sender">Innocent J</em>
                </footer>                
            </article>            
            </div>
        </div>
    </div>
</section>
